orbs:
  ruby: circleci/ruby@2.1.0
  macos: circleci/macos@2.4.0

commands:
  prepare_ios_prerequisites:
    steps:
      - macos/preboot-simulator:
          platform: "iOS"
          version: "17.2"
          device: "iPhone 15"
      - run:
          name: Extract ASC Credential
          command: |
            dirname $PARRA_ASC_API_KEY_PATH | xargs mkdir -p
            echo $ASC_API_KEY | base64 --decode > $PARRA_ASC_API_KEY_PATH
      - macos/add-uitest-permissions
      - macos/install-rosetta
      - ruby/install-deps
      - run:
          name: Install Brew Dependencies
          command: ./scripts/ci/install-brew-dependencies.sh

executors:
  macos-m1-test-runner:
    macos:
      xcode: 15.1.0
    resource_class: macos.m1.large.gen1
    environment:
      PARRA_TEST_DERIVED_DATA_DIRECTORY: build/unit-tests/derivedData
      PARRA_TEST_OUTPUT_DIRECTORY: artifacts/unit-tests
      PARRA_TEST_PROJECT_NAME: ./Parra.xcodeproj
      PARRA_TEST_SCHEME_NAME: Parra
      PARRA_TEST_CONFIGURATION: Debug
      PARRA_TEST_DESTINATION: platform=iOS Simulator,name=iPhone 15,OS=17.2
      PARRA_ASC_API_KEY_PATH: ./artifacts/asc-key.p8
    working_directory: ~/project

version: 2.1
jobs:
  build-and-test:
    executor: macos-m1-test-runner
    steps:
      - checkout
      - prepare_ios_prerequisites
      - run:
          name: Build for Testing
          command: ./scripts/ci/build-for-testing.sh
      - macos/wait-until-simulator-booted
      - run:
          name: Run Unit Tests
          command: ./scripts/ci/run-unit-tests.sh
      - store_artifacts:
          path: artifacts
      - store_test_results:
          # TODO: This is for build, no artifacts are generated for tests yet??
          path: artifacts/junit-results.xml

workflows:
  run-unit-tests:
    jobs:
      - build-and-test
