version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: 15.0.0
    resource_class: macos.x86.medium.gen2
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

workflows:
  run-unit-tests:
    jobs:
      - build-and-test
