orbs:
  ruby: circleci/ruby@2.1.0
  macos: circleci/macos@2.4.0

version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: 15.1.0
    resource_class: macos.m1.medium.gen1
    environment:
      PARRA_TEST_DERIVED_DATA_DIRECTORY: build/unit-tests/derivedData
      PARRA_TEST_PROJECT_NAME: ./Parra.xcodeproj
      PARRA_TEST_SCHEME_NAME: Parra
      PARRA_TEST_CONFIGURATION: Debug
      PARRA_TEST_DESTINATION: generic/platform=iOS,name=iPhone 15,OS=latest
    working_directory: ~/project
    steps:
      - checkout
      - macos/add-uitest-permissions
      - macos/install-rosetta
      - ruby/install-deps
      - run:
          name: Install Brew Dependencies
          command: ./scripts/ci/install-brew-dependencies.sh
      - run:
          name: Build for Testing
          command: ./scripts/ci/build-for-testing.sh
      - store_artifacts:
          path: output
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

workflows:
  run-unit-tests:
    jobs:
      - build-and-test
