name: Build and Run XCTests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-12
    strategy:
      matrix:
        include:
          - xcode: "13.2"
            ios: "15.2"
          - xcode: "14.2"
            ios: "16.2"
    name: Parra Tests on iOS (${{ matrix.ios }})

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_${{ matrix.xcode }}.app && /usr/bin/xcodebuild -version
      - name: Run Parra Core Unit Tests
        run: xcodebuild test -scheme ParraCoreTests -project Parra.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 13,OS=${{ matrix.ios }}' | xcpretty && exit ${PIPESTATUS[0]}

      # - name: Run Core tests
      #   run: xcodebuild test -project Parra.xcodeproj -scheme ParraCore -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.2'
