name: Build and Run XCTests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-13
    strategy:
      matrix:
        include:
          - xcode: "14.3.1"
            ios: "16.4"
            device: "iPhone 14"
    name: Parra Tests on iOS (${{ matrix.ios }})

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_${{ matrix.xcode }}.app && /usr/bin/xcodebuild -version
      - name: Run Parra Core Unit Tests
        run: xcodebuild test -scheme ParraCore -project Parra.xcodeproj -sdk iphonesimulator -testPlan ParraCore -destination 'platform=iOS Simulator,name=${{ matrix.device }},OS=${{ matrix.ios }}' | xcpretty && exit ${PIPESTATUS[0]}
