name: Build and Run XCTests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Core tests
        run: xcodebuild test -scheme ParraCoreTests -project Parra.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.5' CODE_SIGNING_ALLOWED=NO
      - name: Run Feedback tests
        run: xcodebuild test -scheme ParraFeedbackTests -project Parra.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.5' CODE_SIGNING_ALLOWED=NO
