name: Build and Run XCTests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests
        run: xcodebuild test -scheme Demo -project Parra.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 12,OS=15.2' CODE_SIGNING_ALLOWED=NO
